### ISSUE TITLE
Background classes using HEX and opacity

### ISSUE THREAD

**Issue by kling90** [sitevision/envision#117]
Background classes seem to use the HEX color and opacity.

```css
.env-bg-color--brand--10 {
    background-color: #6892d5;
    opacity: .1;
}
```
Makes it pretty hard to use as a background color since the content will have opacity as well.

Could use the built in function `fade-out` instead for the same result?
Or event `lighten` so you don't need a white background.

With fade-out the result would be this:
```css
.env-bg-color--brand--10 {
    background-color: rgba(0,109,255,.1)
}
```

`colors.scss`
```css
$colors: (
   brand: $color-brand,
   success: $color-success,
   warning: $color-warning,
   info: $color-info,
   danger: $color-danger,
   base: $color-base,
   darker: $color-darker,
   dark: $color-dark,
   normal: $color-normal,
   light: $color-light,
   lighter: $color-lighter,
   lightest: $color-lightest,
   hover: $color-hover
);

$transparency: (
   80: .8,
   60: .6,
   40: .4,
   20: .2,
   10: .1
);

@each $state, $color in $colors {
   .#{$prefix}-color--#{$state} {
      color: $color !important;
   }

   .#{$prefix}-bg-color--#{$state} {
      background-color: $color;
   }

   @each $opacity, $value in $transparency {
      .#{$prefix}-bg-color--#{$state}--#{$opacity} {
         background-color: fade-out($color, (1 - $value));
      }
   }
}
```

Can make a pull request if you're interested.
